# Generated by Django 5.2.4 on 2025-07-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_first_name_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='eventDay',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
