# Generated by Django 5.2.4 on 2025-07-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_eventday_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dia_ocupado',
            field=models.IntegerField(null=True),
        ),
    ]
